### PR TITLE
Add count method

### PR DESCRIPTION
**Pull request by cwsaylor**

### CODE REVIEW

**Comment by brupm** [comment]
I vote in favor of the lib keeping a CHANGELOG, @divoxx ?

**Comment by divoxx** [comment]
@brupm honest question: why do you think it's necessary at this point? commits log too cluttered? I like changelogs but I'm kinda in between since it doesn't change as much so it's easy to parse the commit logs and then it's less overhead and one less thing to forget to update.

**Comment by brupm** [comment]
A CHANGELOG requires you to think of a good descriptive sentence about what
changed (not always the case for commit messages). Also could come in handy
when we break backwards compatibility.


On Thu, Apr 30, 2015 at 4:47 PM, Rodrigo Kochenburger <
notifications@github.com> wrote:

> @brupm <https://github.com/brupm> honest question: why do you think it's
> necessary at this point? commits log too cluttered? I like changelogs but
> I'm kinda in between since it doesn't change as much so it's easy to parse
> the commit logs and then it's less overhead and one less thing to forget to
> update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/doximity/es-elasticity/pull/8#issuecomment-98002330>.
>



-- 
- Bruno

**Comment by brupm** [comment]
What's the status of this?

**Comment by cwsaylor** [comment]
I need to test locally one last time then I can merge it in

**Comment by divoxx** [comment]
By the way, I see there is 0.3.6 already on rubygems. Did you release it? Versions should be cut from master, not PRs

**Comment by cwsaylor** [comment]
I did not. I just bumped the number for when I merge into master. Someone else beat me to 0.3.6

**Comment by divoxx** [comment]
Ah, cool. We'll bump to 0.3.7 after merged then.

**Pull request merged**
